### ISSUE TITLE
buildingnet - point cloud

### ISSUE THREAD

**Issue by suyanfei** [buildingnet/buildingnet_dataset#3]
Dear authors,
Thanks for your work.
When I use the point cloud of the building_net dataset, I find a lot of problems in the point cloud. I want to look for your help. I will give a few examples to illustrate as follow ：
（1）in the COMMERCIALchurch_mesh3114 and COMMERCIALcity_hall_mesh0514,   the undetermined point clouds clearly should belong to other categories, however, they are labeled as 0.  Every point cloud file has the same problem.  
（2）in the COMMERCIALhotel_building_mesh0130,  There are points in the column category that should belong to the railing and window. There are other similar misclassifications. These errors are found through visualization.
 (3) Other point clouds have the same problem. I think it will take a lot of effort to correct these mistakes， thank you for your 
   dedication. 
will you release a new version?  I want to use the dataset to support your work, But the error rate of the current version of the dataset is difficult to use. I hope my suggestions are helpful to you.

**Comment by buildingnet** [comment]
Hi. Thanks for showing interest in our work.

Such misclassification examples are fairly common in deep learning datasets and can be found even in the most popular ones. Since we want to keep improving our dataset, we are planning to release a new version (v1) of BuildingNet, with updated semantic labels. We hope that the v1 version will better fit the needs of your work.
